"""Add description column to subtask table

Revision ID: ef1788058ac3
Revises: 
Create Date: 2024-04-04 00:33:52.465512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1788058ac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
